/// Flutter icons JariIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JariIcons
///      fonts:
///       - asset: fonts/JariIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class JariIcons {
  JariIcons._();

  static const _kFontFam = 'JariIcons';
  static const _kFontPkg = null;

  static const IconData milk = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pot_cirl = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pot_dessert = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pot_rect = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_bottle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danone_ferme = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danone_fromage = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danone_jus = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danone_yaourt = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danone_any = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danone_brasse = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danone_dessert = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
